### ISSUE TITLE
Update CameraX to 1.2.2

### ISSUE THREAD

**Issue by vanshg** [ujizin/Camposer#13]
**Is your feature request related to a problem? Please describe.**
This library currently uses CameraX version 1.1.0. Since then, 1.2.2 has been released (and 1.3.0 is in the works). The new version adds new features and fixes bugs

**Describe the solution you'd like**
- Update the libraries to 1.2.2

**Describe alternatives you've considered**
- Forcing the version to 1.2.2 in my own app crashes the SDK
- Waiting until 1.3.0, which seems like it will have a bevy of new features

**Are you willing to provide a PR?**
If it's as simple as bumping the version, sure. However, there are new features in 1.2.x that may be worth integrating (such as `ZERO_SHUTTER_LAG`, `MLKitAnalyzer`

**Comment by ujizin** [comment]
I've already implemented `ZERO_SHUTTER_LAG` and compatibility for `MLKitAnalyzer` on `rememberImageAnalyzer`. 

But I'll release the version `0.2.1` of the library only with the updated dependencies ASAP (maybe tonight), and later another one with the new features. 

Thanks for contributing @vanshg, have a wonderful day!
