### ISSUE TITLE
ByteArray as return on ImageCaptureResult

### ISSUE THREAD

**Issue by koolfreak** [ujizin/Camposer#2]
Would like to ask if, would be supported on future releases the raw ByteArray output? i think this a good option that there were no more file save on the storage and the user can retake a picture.

Also how do I make a retake a picture functionality?

Cheers!

**Comment by koolfreak** [comment]
i already figured out the solution:

```
val baos = ByteArrayOutputStream()
val outputOptions =   ImageCapture.OutputFileOptions.Builder(baos).build()
cameraState.takePicture(outputOptions) { result ->
          if (result is ImageCaptureResult.Success) {
              // baos here with capture image
         }
```

**Comment by lectricas** [comment]
I got my image rotated 90 degrees. How can I fix this?

@ujizin 

Btw, the ImageCapture case worked without any problems.
