### ISSUE TITLE
Provide way to access underlying CameraController

### ISSUE THREAD

**Issue by vanshg** [ujizin/Camposer#20]
**Is your feature request related to a problem? Please describe.**

The specific use case I'm looking to solve is to know when the camera tap-to-focus has completed. The current tap-to-focus functionality does not hook into `CameraController#getTapToFocusState` and seems to rely on an arbitrary delay to consider the focusing "done". 

While this should theoretically be independently solvable, the more general "issue" here is the availability of the data but a restrction on access. Since CameraController is the interface to the Camera, it would be nice if that was directly exposed instead of needing native support within the library for a specific feature.

**Describe the solution you'd like**

It would be nice if the `controller` property in `CameraState` was publicly accessible (currently it is declared as `internal`)

The KDoc for the property in this library even says itself (emphasis mine): `Main controller from CameraX. **useful in cases that haven't been release some feature yet**.`

And yet it cannot be useful if it is not marked as `public`

**Comment by ujizin** [comment]
Hey @vanshg !

I misunderstood it. The `onFocus` lambda is intended for the focusTapContent in the composable, not for CameraController#getTapToFocusState. Maybe I'll need to rename and refactor this later 🤔

Nevertheless, I appreciate your pull request and I'll accept it. I'm going to work on releasing another version ASAP.

Thanks a lot!
