### ISSUE TITLE
add control the exposure？

### ISSUE THREAD

**Issue by Eiffelyk** [ujizin/Camposer#22]
Can the functionality of manually controlling exposure be added? Add left-right swipe on the preview to control the exposure

**Comment by vanshg** [comment]
In the latest release (`0.2.2`), access to the raw `CameraController` was made available (https://github.com/ujizin/Camposer/pull/21).

This gives you the flexibility to implement your custom features. i.e. now you can do `cameraState.controller.cameraControl?.setExposureCompensationIndex(...)`

**Comment by Eiffelyk** [comment]
thanks
