### ISSUE TITLE
Add takePicture with ImageCapture and update camera to 1.3 

### ISSUE THREAD

**Issue by lectricas** [ujizin/Camposer#26]
Lib can now only save pictures to filesystem, I need to store them into ram only.

Also, 1.3 version provides new methods of recording, so some things has to be modified. 

Sorry no time for PR :((((

Lib works, thanks for that though...

**Comment by ujizin** [comment]
Hey @lectricas, regarding storing into RAM, you can check out this [issue](https://github.com/ujizin/Camposer/issues/2#issuecomment-1341270918).

As for CameraX 1.3, I'm also looking forward to the update. However, it's still in beta. Once version 1.3.0 becomes stable, I'll definitely make the update!

Thanks for the support! 😄

**Comment by lectricas** [comment]
Neat, thanks!
