### ISSUE TITLE
Help how to add a semi-transparent layer used to crop image?

### ISSUE THREAD

**Issue by MansonLuo** [ujizin/Camposer#35]
it somehow like QR code scanner, that has a semi-transpatent layer to limit the scan area.
could you suggest me some keyeords that I can search in google to learn hoe to integrate this or some useful information.
Thank you

**Comment by ujizin** [comment]
Hey @MansonLuo, sorry for the delay!  I was moving out and I haven't had much time lately

But for your question, you can use the image analyzer for QRCode. there's an example on [sample app](https://github.com/ujizin/Camposer/blob/03bd85d1e8e9d091bcd98d3a1ef8d81c45ee7977/sample/src/main/java/com/ujizin/sample/feature/camera/CameraScreen.kt#L101), you also can check the [wiki](https://github.com/ujizin/Camposer/wiki/Image-analyzer) for more information 

Now for the **semi-transparent layer**, you can create your custom on **content** parameter

```Kotlin
// Sample canvas for QR code
@Composable
fun QRCodeMask(
  modifier: Modifier = Modifier
) {
  Canvas(
    modifier = modifier, 
    onDraw = {
      val circlePath = Path().apply {
          addRect(Rect(center, size.minDimension / 3))
      }
      clipPath(circlePath, clipOp = ClipOp.Difference) {
          drawRect(SolidColor(Color.Black.copy(alpha = 0.8f)))
      }
    }
  )
}

@Composable
fun QRCodeCamera() {
  CameraPreview() {
    // Here!
    QRCodeMask(Modifier.fillMaxSize())
    // Code...
  }
}
```
---

### Result:

<img width="325" alt="Screenshot 2023-12-10 at 02 05 18" src="https://github.com/ujizin/Camposer/assets/51065868/02963cfb-46d4-4809-9ead-87a01829d6a4">

**Comment by ujizin** [comment]
Since this is not a part of the library, I will close the issue. However, feel free to ask any questions you may have.
