### ISSUE TITLE
I want to adjust the photo processing strategy after taking photos, I don't want the photos taken to be synchronized to the album to show up, what adjustments do I need to make?

### ISSUE THREAD

**Issue by artillerymans** [ujizin/Camposer#53]

**Comment by ujizin** [comment]
Hello @artillerymans, if I understood correctly, you can get the image as a byte array and apply your processing strategy afterwards:

```Kotlin
val baos = ByteArrayOutputStream()
val outputOptions = ImageCapture.OutputFileOptions.Builder(baos).build()
cameraState.takePicture(outputOptions) { result ->
    if (result is ImageCaptureResult.Success) {
        // baos contains the captured image
    }
}
```
This way, your photo will not be synchronized anywhere and will only exist in the byte array

**Comment by artillerymans** [comment]
> Hello @artillerymans, if I understood correctly, you can get the image as a byte array and apply your processing strategy afterwards:
> 
> ```kotlin
> val baos = ByteArrayOutputStream()
> val outputOptions = ImageCapture.OutputFileOptions.Builder(baos).build()
> cameraState.takePicture(outputOptions) { result ->
>     if (result is ImageCaptureResult.Success) {
>         // baos contains the captured image
>     }
> }
> ```
> 
> This way, your photo will not be synchronized anywhere and will only exist in the byte array

extremely grateful @ujizin
