### ISSUE TITLE
Documentation example raise type mismatch

### ISSUE THREAD

**Issue by mgrazianoc** [ujizin/Camposer#8]
**please complete the following information**

**Describe the bug**
Following the [How To Use](https://github.com/ujizin/Camposer#how-to-use) first example, the following error message pops up:

```kt
Type mismatch.
Required: CamSelector
Found: MutableState<CamSelector>
```

**To Reproduce**
Just follow the documentation.

**Expected behavior**
Same behavior as expected in the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/22849928/211115805-2ba238a2-3c4c-427a-b698-87fdf3dd22ef.png)
![image](https://user-images.githubusercontent.com/22849928/211115461-9cba9343-833d-47ac-a692-da396fe9a417.png) 

**Are you willing to provide a PR?**
I can. If I understood correctly what is the expected behavior: between `CameraPreview` to receive a `mutableStateOf<CamSelector>` or just the `CamSelector`, the second one is the intended one. So just fixing the documentation would be the solution.

**Comment by ujizin** [comment]
Hey @mgrazianoc, it needs to use delegates on `CamSelector`

```Kotlin
val cameraSelector by rememberCameraSelector(CamSelector.Back)
```

And thanks for opening the issue! I'll fix the documentation ASAP!
